routes/web.php
<?php

use App\Http\Controllers\ProfileController;
use App\Http\Controllers\PostController;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Session;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/
// Route::get('/', HomeController::class)->name('home');
Route::get('home',function(){
    return 'h';
})->name('home');
Route::get('about',function(){
    return 'h';
})->name('about');

Route::get('contact',function(){
    return 'h';
})->name('contact');


Route::get('/', function () {
    return view('welcome');
});

Route::get('/test', function (Request $request) {
    // $data = $request->session()->all();

    $data = $request->expectsJson();
    dd($data);

});
Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});
require __DIR__ . '/auth.php';

Route::group(['middleware'=>'auth'],function(){
    Route::get('posts/trash', [PostController::class, 'trashed'])->name('posts.tarshed');
    Route::get('posts/{id}/restore', [PostController::class, 'restore'])->name('posts.restore');
    Route::delete('posts/{id}/force_delete', [PostController::class, 'forcedelete'])->name('posts.force_delete');
    Route::resource('posts', PostController::class);
});
/** CRUD */


Route::get('user-data',function(){
    $user = Auth::user()->name; //ดึงข้อมูล ออกมาคล้าย session
    $test = auth()->user()->email;
    // return $user;
});

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Post extends Model
{
    use HasFactory ,SoftDeletes;
    protected $fillable = [
        'title',
        'description',
        'status',
        'publish_date',
        'images',
        'user_id',
        'category_id',
        'views',
    ];
    
    // protected $guarded = [
    //     'title',
    // ];


    /**
     * belongsTo ใน Laravel คือการกำหนดความสัมพันธ์ระหว่างโมเดลในลักษณะ "Belongs To" หรือ "เป็นส่วนหนึ่งของ"
     *ในระบบฐานข้อมูล ความสัมพันธ์นี้จะเชื่อมโยงโมเดลหนึ่งไปยังโมเดลอื่น แสดงถึงว่า โมเดลหนึ่งเป็นส่วนย่อยหรือมีความเกี่ยวข้องกับโมเดลอีกตัวหนึ่งในฐานข้อมูล
     *ใน Laravel, belongsTo ใช้สำหรับกำหนดความสัมพันธ์ระหว่างโมเดล โดยการระบุโมเดลที่เกี่ยวข้องกับโมเดลปัจจุบัน และสามารถใช้ได้ในทั้ง "One-to-One"
     *และ "One-to-Many" ความสัมพันธ์ โดยการใช้คีย์ต่างหากที่เรียกว่า "foreign key" เพื่อบ่งชี้ถึงแถวในตารางที่เกี่ยวข้อง
     */
    public function category()
    {
        return $this->belongsTo(Category::class);
    }
    /**
     * belongsToMany ใน Laravel คือการระบุความสัมพันธ์ของโมเดลระหว่างสองโมเดลแบบ "Many-to-Many" หรือ "มากต่อมาก"
     * ในระบบฐานข้อมูล โดยโมเดลสองตัวจะมีความสัมพันธ์กันหลายต่อหลาย คือ หนึ่งโมเดลสามารถมีความสัมพันธ์กับหลายโมเดลของอีกโมเดลหนึ่ง
     * และโมเดลดังกล่าวก็สามารถมีความสัมพันธ์กับโมเดลอื่นๆ ได้เช่นกันใน Laravel, เราใช้ belongsToMany เพื่อกำหนดความสัมพันธ์ระหว่างโมเดล
     * และใช้งานร่วมกับตารางกลางที่ใช้เพื่อเก็บข้อมูลเกี่ยวกับความสัมพันธ์นี้ โดยในตารางกลางนี้จะเก็บข้อมูลที่เชื่อมโยงระหว่างสองโมเดลรวมถึงข้อมูลเพิ่มเติม
     * ที่เกี่ยวข้องกับความสัมพันธ์นี้ด้วย เช่น ตารางกลางสามารถเก็บข้อมูลเพิ่มเติมเกี่ยวกับวันที่เริ่มและสิ้นสุดของความสัมพันธ์ระหว่างสองโมเดลได้
     */
    public function tags()
    {
        return $this->belongsToMany(Tag::class);
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;
use App\Models\Post;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\File; //พวกเกียวกับ file

class PostController extends Controller
{

    public function __construct()
    {
        //$this->middleware('authCheck2')->only(['create','show']); // เรียกว่าการเช็ค middleware ผ่าน controller ส่วนในของ only คือไม่อนุญาติให้ function ต่อไปนี้เข้าได้
        //$this->middleware('authCheck2')->except(['index','show','create']); //อนุญาติให้ function ต่อไปนี้เข้าถึงได้
    }
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        try {
            $data = [
                'title' => 'การทำ CURD',
                'posts'  => Cache::remember('posts-page-'.request('page',1),3, function(){ //ดึงข้อมูล posts 
                    return Post::with('category')->paginate(10);
                }),
                // 'posts'  => Cache::rememberForever('posts', function(){
                //     return Post::with('category')->paginate(10);
                // })
            ];
            return view('posts.index', $data);
        } catch (\Throwable $th) {
            throw $th;
        }
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        try {
            $data = [
                'title' => 'การทำ create from',
                'categories' => Category::all()
            ];

            return view('posts.create', $data);
        } catch (\Throwable $th) {
            throw $th;
        }
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $request->validate([
            'image' => ['required', 'image'],
            'title' => ['required', 'max:100'],
            'category_id' => ['required', 'integer'],
            'description' => ['required']
        ], [
            'image.required' => 'กรุณาเลือกไฟล์ที่จะอัพโหลดรูป',
            'image.image' => 'อัพได้เฉพาะไฟล์รูปเท่านั้น',

            'title.required' => 'กรุณาใส่ข้อมูลลงในช่องหัวข้อ',
            'title.max' => 'รับขนาดตัวอักษรสูงสุดไม่เกิน 100 ตัว',

            'category_id.required' => 'กรุณาเลือกหมวดรายการ',

            'description.required' => 'กรุณากรอกรายละเอียด'
        ]);
        $fileName = time() . '.' . $request->image->extension();
        $filePath = $request->image->storeAs('uploads', $fileName);

        $posts = Post::create([
            'title' => $request->title,
            'description' => $request->description,
            'images' => 'storage/' . $filePath,
            'publish_date' => date('Y-m-d'),
            'user_id' => rand(1, 4),
            'category_id' => $request->category_id,
            'views' => rand(1, 500),
            'status' => 1
        ]);

        if ($posts) {
            return redirect()->route('posts.index');
        } else {
            dd('flase');
        }

        //  $create = Post::insert([
        //     'title' => $request->title,
        //  ]);
        //  dd('success');
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        try {
            $data = [
                'title' => 'รายละเอียด',
                'posts' => Post::findOrFail($id)
            ];
            return view('posts.show', $data);
        } catch (\Throwable $th) {
            throw $th;
        }
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        //
        try {
            $data = [
                'title' => 'edit from',
                'post'  => Post::findOrFail($id),
                'category' => Category::all()
            ];
            return view('posts.edit', $data);
        } catch (\Throwable $th) {
            throw $th;
        }
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        $request->validate([
            'title' => ['required', 'max:100'],
            'category_id' => ['required', 'integer'],
            'description' => ['required']
        ], [
            'title.required' => 'กรุณาใส่ข้อมูลลงในช่องหัวข้อ',
            'title.max' => 'รับขนาดตัวอักษรสูงสุดไม่เกิน 100 ตัว',

            'category_id.required' => 'กรุณาเลือกหมวดรายการ',

            'description.required' => 'กรุณากรอกรายละเอียด'
        ]);
        $post = Post::findOrFail($id);
        if ($request->hasFile('file')) {
            $request->validate([
                'file' => ['required', 'image']
            ], [
                'file.required' => 'กรุณาเลือกไฟล์ที่จะอัพโหลดรูป',
                'file.image' => 'อัพได้เฉพาะไฟล์รูปเท่านั้น',
            ]);
            $fileName = time() . '.' . $request->file->extension();
            $filePath = $request->file->storeAs('uploads', $fileName);
            File::delete(public_path($post->images));
            $post->images = 'storage/' . $filePath;
        }
        $post->title = $request->title;
        $post->description = $request->description;
        $post->publish_date  = date('Y-m-d');
        $post->user_id = rand(1, 4);
        $post->category_id = $request->category_id;
        $post->views = rand(1, 999);
        $post->status = rand(0, 1);
        $post->save();
        return redirect()->route('posts.index');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        //
        $post = Post::findOrFail($id);
        $post->delete($id);
        return redirect()->route('posts.index');
    }

    public function trashed()
    {
        try {
            $data = [
                'title' => 'การทำ trashed',
                'posts'  => Post::onlyTrashed()->get()
            ];
            return view('posts.trashed', $data);
        } catch (\Throwable $th) {
            throw $th;
        }
    }

    public function restore(string $id){
        $post = Post::onlyTrashed()->findOrFail($id);
        $post->restore();
        return redirect()->back();
    }
    public function forcedelete(string $id){
        $post = Post::withTrashed()->findOrFail($id);
        File::delete(public_path($post->images));
        $post->forceDelete();
        return redirect()->back();
    }
}

resources/views/posts/create.blade.php
@extends('layouts.layouts_.master_layout')
@section('title')
    {{ $title }}
@endsection
@section('content')
    <main class="container mt-3" role="main">
        <div class="row mt-5">
            <div class="col-12 mx-auto">
                <div class="card rounded-bottom">
                    <div class="card-header bg-primary text-white">
                        <div class="row">
                            <div class="col-md-6">
                                <h4>Create Posts</h4>
                            </div>
                            <div class="col-md-6 d-flex justify-content-end">
                                <a href="{{ route('posts.index') }}" class="btn btn-success mx-1">Back</a>
                            </div>
                        </div>
                    </div>

                    <div class="card-body">
                        <div class="row mb-3">
                            @if ($errors->any())
                                @foreach ($errors->all() as $error)
                                    <div class="alrt alert-danger">{{ $error }}</div>
                                @endforeach
                            @endif
                        </div>

                        <form action="{{ route('posts.store') }}" method="post" enctype="multipart/form-data">
                            @csrf
                            <div class="row mb-3">
                                <div class="form-group col-md-6">
                                    <div>
                                        <label for="" class="form-label">รูปภาพ</label>
                                        <input type="file" name="image" id="image" class="form-control">
                                    </div>
                                </div>
                                <div class="form-group col-md-6">
                                    <div>
                                        <label for="" class="form-label">หัวข้อ</label>
                                        <input type="text" name="title" id="title" class="form-control">
                                    </div>
                                </div>
                                <div class="form-group col-md-12">
                                    <div>
                                        <label for="" class="form-label">หมวดหมู่</label>
                                        <select name="category_id" id="category_id" class="form-control">
                                            <option value="#">เลือกรายการ</option>
                                            @isset($categories)
                                                @foreach ($categories as $categories)
                                                    <option value="{{ $categories->id }}">{{ $categories->name }}</option>
                                                @endforeach
                                            @endisset
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group col-md-12">
                                    <div>
                                        <label for="" class="form-label">รายละเอียด</label>
                                        <textarea class="form-control" placeholder="description" name="description" id="description" cols="30"
                                            rows="10"></textarea>
                                    </div>
                                </div>
                                <div class="form-group col-md-12">
                                    <button type="submit" class="btn btn-primary w-100 mt-3 rounded">Create</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div><br><br><br><br><br><br>
    </main>
@endsection

resources/views/posts/edit.blade.php
@extends('layouts.layouts_.master_layout')
@section('title')
    {{ $title }}
@endsection
@section('content')
    <main class="container mt-3" role="main">
        <div class="row mt-5">
            <div class="col-12 mx-auto">
                <div class="card rounded-bottom">
                    <div class="card-header bg-primary text-white">
                        <div class="row">
                            <div class="col-md-6">
                                <h4>Edit Posts</h4>
                            </div>
                            <div class="col-md-6 d-flex justify-content-end">
                                <a href="{{ route('posts.index') }}" class="btn btn-success mx-1">Back</a>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="row mb-3">
                            @if ($errors->any())
                                @foreach ($errors->all() as $error)
                                    <div class="alrt alert-danger">{{ $error }}</div>
                                @endforeach
                            @endif
                        </div>
                        <form action="{{ route('posts.update', $post->id) }}" method="post" enctype="multipart/form-data">
                            @csrf
                            @method('PUT')
                            <div class="row mb-3">
                                <div class="form-group col-12">
                                    <img src="{{ asset($post->images) }}" alt="" width="200px">

                                </div>
                                <div class="form-group col-md-6">
                                    <div>
                                        <label for="" class="form-label">รูปภาพ</label>
                                        <input type="file" name="file" id="file" class="form-control"
                                            value="{{ $post->images }}">
                                    </div>
                                </div>
                                <div class="form-group col-md-6">
                                    <div>
                                        <label for="" class="form-label">หัวข้อ</label>
                                        <input type="text" name="title" id="title" class="form-control"
                                            value="{{ $post->title }}">
                                    </div>
                                </div>
                                <div class="form-group col-md-12">
                                    <div>
                                        <label for="" class="form-label">หมวดหมู่</label>
                                        <select name="category_id" id="category_id" class="form-control">
                                            <option value="">เลือกรายการ</option>
                                            @isset($category)
                                                @foreach ($category as $categorys)
                                                    <option value="{{ $categorys->id }}"
                                                        {{ $categorys->id == $post->category_id ? 'selected' : '' }}>
                                                        {{ $categorys->name }}</option>
                                                @endforeach
                                            @endisset

                                        </select>
                                    </div>
                                </div>
                                <div class="form-group col-md-12">
                                    <div>
                                        <label for="" class="form-label">รายละเอียด</label>
                                        <textarea class="form-control" placeholder="description" name="description" id="description"cols="30"
                                            rows="10">
                                            {{ $post->description }}
                                        </textarea>
                                    </div>
                                </div>
                                <div class="form-group col-md-12">
                                    <button type="submit" class="btn btn-primary w-100 mt-3 rounded">Update</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div><br><br><br><br><br><br>
    </main>
@endsection

resources/views/posts/index.blade.php
@extends('layouts.layouts_.master_layout')
@section('title')
    {{ $title }}
@endsection
@section('content')
    <style>
        a {
            text-decoration: none;
        }
    </style>
    <main class="container mt-3" role="main">
        <div class="row mt-5">
            <div class="col-12 mx-auto">
                <div class="card rounded-bottom">
                    <div class="card-header bg-primary text-white">
                        <div class="row">
                            <div class="col-md-6">
                                <h4>All Posts</h4>
                            </div>
                            <div class="col-md-6 d-flex justify-content-end">
                                <a href="{{ route('posts.create') }}" class="btn btn-success mx-1">Create</a>
                                <a href="{{ route('posts.tarshed') }}" class="btn btn-dark mx-1">Trashed</a>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <table class="table table-striped">
                            <thead class="bg-primary text-white rounded">
                                <tr>
                                    <th scope="col"style="width:5%"class="text-center">#</th>
                                    <th scope="col"style="width:10%">Title</th>
                                    <th scope="col"style="width:30%">Description</th>
                                    <th scope="col"style="width:10%">Category</th>
                                    <th scope="col"style="width:10%">Publish Date</th>
                                    <th scope="col"style="width:35%">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @isset($posts)
                                    {{--  ตัวอย่างการแบ่ง pagetion แบบนับเลขกรณีไปหน้าที่2 ก็นับเลขต่อเลยไม่นับใหม่ --}}
                                    @php
                                        $rowNumber = ($posts->currentPage() - 1) * $posts->perPage();
                                    @endphp
                                    @
                                    @foreach ($posts as $key => $post)
                                        <tr>
                                            <th scope="col" class="text-center">{{ ++$rowNumber }}</th>
                                            <td scope="col"><img src="{{ asset($post->images) }}"
                                                    width="80"alt=""></td>
                                            <td scope="col">{{ Str::limit($post->description, 80) }}</td>
                                            <td scope="col">
                                                <div class="btn-sm btn-primary">{{ $post->category->name }}</div>
                                            </td>
                                            <td scope="col">{{ date('d/m/Y', strtotime($post->publish_date)) }}</td>
                                            <td scope="col">
                                                <a href="{{ route('posts.show', $post->id) }}"
                                                    class="btn-sm btn-success">Show</a>
                                                <a href="{{ route('posts.edit', $post->id) }}"
                                                    class="btn-sm btn-primary">Edit</a>
                                                <form action="{{ route('posts.destroy', $post->id) }}" method="post">
                                                    @csrf
                                                    @method('DELETE')
                                                    <button class="btn-sm btn-danger" type="submit">Delete</button>
                                                </form>
                                            </td>
                                        </tr>
                                    @endforeach
                                @endisset
                            </tbody>
                        </table>
                        {{-- ทำ pagetion  --}}
                        {{-- ให้ไปไฟล์ AppServiceProvider --}}
                        <div class="d-flex justify-content-end">
                            {!! $posts->links() !!}
                        </div>
                    </div>
                </div>
            </div>
        </div><br><br><br><br><br><br>
    </main>
@endsection

resources/views/posts/show.blade.php
@extends('layouts.layouts_.master_layout')

@section('title') {{$title}} @endsection
@section('content')
<style>
    a{
    text-decoration: none;
    }
</style>
<main class="container mt-3" role="main">
    <div class="row mt-5">
        <div class="col-12 mx-auto">
            <div class="card rounded-bottom">
                <div class="card-header bg-primary text-white">
                    <div class="row">  
                        <div class="col-md-6">
                            <h4>Detail</h4>
                        </div>
                        <div class="col-md-6 d-flex justify-content-end">
                            <a href="{{route('posts.index')}}" class="btn btn-success mx-1">Back</a>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <table class="table table-striped table-bordered">
                        <tbody>
                            <tr>
                                <th width="25%">id</th>
                                <th scope="col">{{$posts->id}}</th>
                            </tr>
                            <tr>
                                <td width="30%">Image</td>
                               <td scope="col"><img src="{{asset($posts->images)}}" width="80"alt=""></td>
                            </tr>    
                            <tr>
                                <td width="20%">Description</td>
                                <td scope="col">{{Str::limit($posts->description,80)}}</td>
                            </tr>
                            <tr>
                                <td width="20%">Category</td>
                                <td scope="col"><div class="btn-sm btn-primary">{{$posts->category->name}}</div></td>
                            </tr>
                            <tr>
                                <td width="20%">Publish Date</td>
                                <td scope="col">{{date('d/m/Y',strtotime($posts->publish_date))}}</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div><br><br><br><br><br><br>
</main>
@endsection

resources/views/posts/trashed.blade.php
@extends('layouts.layouts_.master_layout')
@section('title')
    {{ $title }}
@endsection
@section('content')
    <main class="container mt-3" role="main">
        <div class="row mt-5">
            <div class="col-12 mx-auto">
                <div class="card rounded-bottom">
                    <div class="card-header bg-primary text-white">
                        <div class="row">
                            <div class="col-md-6">
                                <h4>Trashed Posts</h4>
                            </div>
                            <div class="col-md-6 d-flex justify-content-end">
                                <a href="{{ route('posts.index') }}" class="btn btn-success mx-1">Back</a>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <table class="table table-striped">
                            <thead class="bg-primary text-white rounded">
                                <tr>
                                    <th scope="col"style="width:5%"class="text-center">#</th>
                                    <th scope="col"style="width:10%">Title</th>
                                    <th scope="col"style="width:30%">Description</th>
                                    <th scope="col"style="width:10%">Category</th>
                                    <th scope="col"style="width:10%">Publish Date</th>
                                    <th scope="col"style="width:15%">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @php
                                    $text = 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Saepe incidunt voluptatum voluptates est esse, asperiores ut minus rem fugit harum tempora fugiat in non mollitia ab, unde laboriosam ea consequatur.';
                                @endphp
                                @isset($posts)
                                    @php
                                        $i = 1;
                                    @endphp
                                    @foreach ($posts as $posts)
                                        <tr>
                                            <th scope="col" class="text-center">{{ $i++ }}</th>
                                            <td scope="col"><img src="{{ asset($posts->images) }}"
                                                    width="80"alt=""></td>
                                            <td scope="col">{{ Str::limit($posts->description, 80) }}</td>
                                            <td scope="col">
                                                <div class="btn-sm btn-primary">{{ $posts->category->name }}</div>
                                            </td>
                                            <td scope="col">{{ date('d/m/Y', strtotime($posts->publish_date)) }}</td>
                                            <td scope="col">
                                                <a href="{{ route('posts.restore', $posts->id) }}"
                                                    class="btn-sm btn-success">Restore</a>
                                                <form action="{{ route('posts.force_delete', $posts->id) }}" method="post" class="mt-3">
                                                    @csrf
                                                    @method('DELETE')
                                                    <button class="btn-sm btn-danger">Delete</button>
                                                </form>

                                            </td>
                                        </tr>
                                    @endforeach
                                @endisset
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div><br><br><br><br><br><br>
    </main>
@endsection